# Generated by Django 4.2.6 on 2023-10-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='debt',
        ),
        migrations.AddField(
            model_name='networknode',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Долг'),
        ),
    ]
